---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elixir-dev.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: elixir-dev
    app.kubernetes.io/instance: elixir-dev
data:
  RELEASE_NAME: "elixir-dev"
  RELEASE_TMP: "/tmp"
  PROBE_PORT: "9090"
#   RABBITMQ_HOST: {{/* include "rabbitmq.hostname" . */}}