---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elixir-dev.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: elixir-dev
    app.kubernetes.io/instance: elixir-dev