---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elixir_dev.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: elixir_dev
    app.kubernetes.io/instance: elixir_dev